run:
  tests: false

linters:
  disable-all: true
  # enable-all: false
  enable:
    - errcheck:
  # fast: false

# all available settings of specific linters
linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  staticcheck:
    fast: true
  unused:
    fast: true
  gosimple:
    fast: true
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 1.0
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: UK
  gocyclo:
    min-complexity: 13
  interfacer:
    fast: true
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 1024
    fast: true
  unparam:
    fast: true
  modules-download-mode: readonly
